### PR TITLE
Support FirefoxDeveloperEdition

### PR DESCRIPTION
**Pull request by jackblackevo**
Hello!
I add FirefoxDeveloperEdition's profile location to info.plist file.
Now can search FirefoxDeveloperEdition bookmarks and history with the keyword: ffd.

### CODE REVIEW

**Comment by nikipore** [comment]
Works and looks great. Thank you!

**Comment by a-x-** [comment]
I have an issue...

FirefoxNightly 58.0a1 (2017-11-02)

> no such column: moz_places.favicon_id

```
[2017-11-02 15:13:42][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "bookmarks.py", line 71, in <module>
    alfred.write(alfred.xml(results(db, query), maxresults=_MAX_RESULTS))
  File "/Users/mxtnr/preferences/alfred/Alfred.alfredpreferences/workflows/user.workflow.44266729-E92C-4956-80E4-E9EC6282DDAC/alfred.py", line 87, in xml
    for item in itertools.islice(items, maxresults):
  File "bookmarks.py", line 38, in results
    for result in db.execute(sql(query)):
sqlite3.OperationalError: no such column: moz_places.favicon_id
```

**Comment by nikipore** [comment]
Should be fixed now (updated binary workflow). See https://github.com/nikipore/alfred-firefoxbookmarks/issues/6

**Comment by a-x-** [comment]
Thank you!

**Pull request merged**
