### PR TITLE
Fix workflow on Firefox 63 and newer

### PR DESCRIPTION
**Pull request by cgioia**
Firefox has started locking the databases in their new versions. Simple workaround is to use a copy of the databases. This is probably a better answer too, since we don't necessarily want to be using their files externally and potentially cause conflicts/corruption.

### CODE REVIEW

**Comment by mwhdc** [comment]
Thanks for the fix, it looks like the original dev no longer uses Firefox. Using your fork and FF 63.0, are you seeing bookmarks in your search results? I'm seeing results from browsing_history only for some reason.

**Comment by nikipore** [comment]
In fact I don't use FF on my Mac any more since they broke most of my relevant add-ons and after [this issue](
https://github.com/nikipore/alfred-firefoxbookmarks/issues/12) I decided that it's time to move on.

I am glad to leave a comment and link to a fork if someone is willing to take over.

**Comment by cgioia** [comment]
I simply made the modification suggested by a commenter in issue #12 and it seems to work for me.

**Comment by cgioia** [comment]
Not sure how to explain that, my bookmark results were near the top. But honestly I didn’t notice the missing bookmarks until your comment above, as I use this workflow and the Awesome Bar 100% for searching and navigating history. So straight-up removing it as you have done wouldn’t work for me.

I may dive into some further enhancements at some point but right now it works well for what I want so no promises. :)

**Comment by nikipore** [comment]
Thanks! I don't use Firefox any more, so I am glad if anyone takes over.

**Comment by cgioia** [comment]
Whoops, I forgot this pull request was sitting open when I pushed to my fork. Thanks for closing it, and I won't open any more given that you're not actively developing it any further. Thanks for doing all the original work though, I still find this workflow useful on an almost-daily basis. 😄

**Pull request merged**
